<?php

namespace AppBundle\Repository;

/**
 * FactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactRepository extends \Doctrine\ORM\EntityRepository
{
}
