<?php

namespace AppBundle\Repository;

/**
 * LeaderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeaderRepository extends \Doctrine\ORM\EntityRepository
{
    public function getBetterLeadersCount(Leader $leader): int //
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        // select count
        $query = $qb->select("l")
            ->from('AppBundle:Leader', 'l')
            ->where(
                $qb->expr()->gt('l.score', $leader->getScore())
            )
            ->andWhere(
                $qb->expr()->lt('l.time', $leader->getTime())
            )
            ->getQuery();
        $result = $query->getResult();

        return count($result);
    }

    public function saveLeader(Leader $leader)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
    }
}
