# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
  numberofquestions: 10
  time: 30
  beginpercentage: 20
  endpercentage: 80
#    parameter_name: value

services:
  facts_fetcher:
    class: AppBundle\Fetcher\FactsFetcher
    arguments: ["%numberofquestions%", "%time%", "%beginpercentage%", "%endpercentage%"]

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
